import 'package:loans/1_domain/entities/loan_entity.dart';

/// Datos de prueba para el demo de la aplicación
class MockData {
  static List<LoanEntity> getMockLoans() {
    return [
      LoanEntity(
        id: '1',
        lenderId: 'current_user',
        borrowerId: 'Ana Martínez',
        amount: 0.0,
        currency: 'USD',
        description: 'Laptop Dell XPS',
        loanDate: DateTime.now().subtract(const Duration(days: 15)),
        dueDate: DateTime.now().add(const Duration(days: 7)),
        status: LoanStatus.active,
        createdAt: DateTime.now().subtract(const Duration(days: 15)),
      ),
      LoanEntity(
        id: '2',
        lenderId: 'current_user',
        borrowerId: 'Laura Sánchez',
        amount: 0.0,
        currency: 'USD',
        description: 'Proyector Epson',
        loanDate: DateTime.now().subtract(const Duration(days: 20)),
        dueDate: DateTime.now().add(const Duration(days: 5)),
        status: LoanStatus.active,
        createdAt: DateTime.now().subtract(const Duration(days: 20)),
      ),
      LoanEntity(
        id: '3',
        lenderId: 'current_user',
        borrowerId: 'Luis Torres',
        amount: 0.0,
        currency: 'USD',
        description: 'Cables HDMI',
        loanDate: DateTime.now().subtract(const Duration(days: 10)),
        dueDate: DateTime.now().subtract(const Duration(days: 2)),
        status: LoanStatus.overdue,
        createdAt: DateTime.now().subtract(const Duration(days: 10)),
      ),
      LoanEntity(
        id: '4',
        lenderId: 'current_user',
        borrowerId: 'Camilo Herrera',
        amount: 0.0,
        currency: 'USD',
        description: 'Disco Externo 2TB',
        loanDate: DateTime.now().subtract(const Duration(days: 5)),
        dueDate: DateTime.now().add(const Duration(days: 10)),
        status: LoanStatus.active,
        createdAt: DateTime.now().subtract(const Duration(days: 5)),
      ),
      LoanEntity(
        id: '5',
        lenderId: 'Jaime Huaylla',
        borrowerId: 'current_user',
        amount: 0.0,
        currency: 'USD',
        description: 'Parlantes JBL',
        loanDate: DateTime.now().subtract(const Duration(days: 30)),
        dueDate: DateTime.now().add(const Duration(days: 2)),
        status: LoanStatus.active,
        createdAt: DateTime.now().subtract(const Duration(days: 30)),
      ),
      LoanEntity(
        id: '6',
        lenderId: 'Carolina Huaylla',
        borrowerId: 'current_user',
        amount: 0.0,
        currency: 'USD',
        description: 'Chocolata 1lts',
        loanDate: DateTime.now().subtract(const Duration(days: 8)),
        dueDate: DateTime.now().add(const Duration(days: 1)),
        status: LoanStatus.active,
        createdAt: DateTime.now().subtract(const Duration(days: 8)),
      ),
      LoanEntity(
        id: '7',
        lenderId: 'Eluida Figueredo',
        borrowerId: 'current_user',
        amount: 0.0,
        currency: 'USD',
        description: 'Monster Peru calipso',
        loanDate: DateTime.now().subtract(const Duration(days: 3)),
        dueDate: DateTime.now().add(const Duration(days: 4)),
        status: LoanStatus.pending,
        createdAt: DateTime.now().subtract(const Duration(days: 3)),
      ),
      LoanEntity(
        id: '8',
        lenderId: 'Carlos Vega',
        borrowerId: 'current_user',
        amount: 0.0,
        currency: 'USD',
        description: 'Smartwatch',
        loanDate: DateTime.now().subtract(const Duration(days: 12)),
        dueDate: DateTime.now().add(const Duration(days: 3)),
        status: LoanStatus.active,
        createdAt: DateTime.now().subtract(const Duration(days: 12)),
      ),
      LoanEntity(
        id: '9',
        lenderId: 'current_user',
        borrowerId: 'Andrés Castro',
        amount: 0.0,
        currency: 'USD',
        description: 'Control Xbox',
        loanDate: DateTime.now().subtract(const Duration(days: 25)),
        dueDate: DateTime.now().add(const Duration(days: 5)),
        status: LoanStatus.pending,
        createdAt: DateTime.now().subtract(const Duration(days: 25)),
      ),
      LoanEntity(
        id: '10',
        lenderId: 'Carolina Vega',
        borrowerId: 'current_user',
        amount: 0.0,
        currency: 'USD',
        description: 'Teclado Mecánico',
        loanDate: DateTime.now().subtract(const Duration(days: 18)),
        dueDate: DateTime.now().add(const Duration(days: 12)),
        status: LoanStatus.active,
        createdAt: DateTime.now().subtract(const Duration(days: 18)),
      ),
      LoanEntity(
        id: '11',
        lenderId: 'current_user',
        borrowerId: 'Juan Pablo',
        amount: 0.0,
        currency: 'USD',
        description: 'Mouse Logitech',
        loanDate: DateTime.now().subtract(const Duration(days: 6)),
        dueDate: DateTime.now().add(const Duration(days: 8)),
        status: LoanStatus.active,
        createdAt: DateTime.now().subtract(const Duration(days: 6)),
      ),
      LoanEntity(
        id: '12',
        lenderId: 'Juan Pablo',
        borrowerId: 'current_user',
        amount: 0.0,
        currency: 'USD',
        description: 'Tablet iPad Pro',
        loanDate: DateTime.now().subtract(const Duration(days: 14)),
        dueDate: DateTime.now().add(const Duration(days: 6)),
        status: LoanStatus.active,
        createdAt: DateTime.now().subtract(const Duration(days: 14)),
      ),
      LoanEntity(
        id: '13',
        lenderId: 'current_user',
        borrowerId: 'Carolina Huaylla',
        amount: 0.0,
        currency: 'USD',
        description: 'TV Samsung 55"',
        loanDate: DateTime.now().subtract(const Duration(days: 35)),
        dueDate: DateTime.now().add(const Duration(days: 15)),
        status: LoanStatus.pending,
        createdAt: DateTime.now().subtract(const Duration(days: 35)),
      ),
      LoanEntity(
        id: '14',
        lenderId: 'Laura Sánchez',
        borrowerId: 'current_user',
        amount: 0.0,
        currency: 'USD',
        description: 'Kit herramientas',
        loanDate: DateTime.now().subtract(const Duration(days: 22)),
        dueDate: DateTime.now().add(const Duration(days: 3)),
        status: LoanStatus.active,
        createdAt: DateTime.now().subtract(const Duration(days: 22)),
      ),
      LoanEntity(
        id: '15',
        lenderId: 'Juan Pablo',
        borrowerId: 'current_user',
        amount: 0.0,
        currency: 'USD',
        description: 'Libros técnicos',
        loanDate: DateTime.now().subtract(const Duration(days: 9)),
        dueDate: DateTime.now().add(const Duration(days: 11)),
        status: LoanStatus.pending,
        createdAt: DateTime.now().subtract(const Duration(days: 9)),
      ),
    ];
  }
}
